# Generated by Django 3.2.9 on 2022-03-12 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=30)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('CKT', 'Cricket'), ('FB', 'Football'), ('T', 'Tennis'), ('BB', 'Basketball'), ('B', 'Badminton'), ('TT', 'Table Tennis')], max_length=3)),
                ('name', models.CharField(max_length=30)),
                ('video_link', models.URLField()),
                ('description', models.TextField()),
                ('completion_status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
