# Generated by Django 3.2.9 on 2022-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220312_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sport',
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(default=68),
        ),
    ]
