# Generated by Django 3.2.9 on 2022-03-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220312_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participant_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
