# Generated by Django 3.2.9 on 2022-03-12 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220312_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.PositiveIntegerField(default=1)),
                ('eventId', models.IntegerField()),
                ('tokenNo', models.CharField(max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JoinedEvent', to='api.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JoinedOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
