# Generated by Django 3.2.9 on 2022-03-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_joinedevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arms', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('legs', models.IntegerField()),
                ('intensive_workout', models.IntegerField()),
                ('push_ups', models.BooleanField(blank=True, default=False, null=True)),
                ('pull_ups', models.BooleanField(blank=True, default=False, null=True)),
                ('plank', models.BooleanField(blank=True, default=False, null=True)),
                ('crunches', models.BooleanField(blank=True, default=False, null=True)),
                ('mountain_climbers', models.BooleanField(blank=True, default=False, null=True)),
                ('jumping_jack', models.BooleanField(blank=True, default=False, null=True)),
                ('squats', models.BooleanField(blank=True, default=False, null=True)),
                ('lunges', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='joinedevents',
            name='eventId',
            field=models.CharField(max_length=50),
        ),
    ]
